/*
/*    default_scribs.cpp
/*
/*    Generated by scrib_compiler.exe on Dec  1 2009 at 07:15:45
/*
/*    Copyright Robert Sacks 2009
*/


const wchar_t * g_apDefaultScribs [] =
{
   L"FileVersionMismatch     = Program file versions do not match.",
   L"FileVersionMismatch     = The EXE requires: \t%s.",
   L"FileVersionMismatch                  = %s is:\t%s.",
   L"FileVersionMismatch                  = %s is:\t%s.",
   L"FileVersionMismatch     = Hint: Try reinstalling the program.",
   L"BadOsVersion     = The program can't run on this version of Windows.",
   L"BadOsVersion     = The program requires Windows XP service pack 1 or higher.",
   L"BadArgument      = Invalid argument in function call.",
   L"BadArgument      = Function: %s.",
   L"BadArgument      = For more information, see the DLL log file.",
   L"LoadScribFile     = Loading language file.",
   L"LoadScribFile     = Lines loaded: %d.",
   L"CannotLoadScribFile    = Loading language file.",
   L"CannotLoadScribFile    = Cannot find file %s.",
   L"CannotLoadScribFile    = The program's text will appear in English.",
   L"CannotLoadScribFile    = Try reinstalling the program.",
   L"InputEvents.MouseMotion       = Mouse motion",
   L"InputEvents.ScrnPosition      = scrn position",
   L"InputEvents.WinPosition       = win position",
   L"InputEvents.KeyName        = Key name",
   L"InputEvents.Event        = event",
   L"InputEvents.VirtualKey       = virtual key",
   L"InputEvents.ScanCode       = scan code",
   L"InputEvents.Extended       = extended",
   L"InputEvents.PreviousKeyState     = prev state",
   0
};

