/*
/*    default_scribs.cpp
/*
/*    Generated by scrib_compiler.exe on Dec 12 2009 at 23:52:06
/*
/*    Copyright Robert Sacks 2009
*/


const wchar_t * g_apDefaultScribs [] =
{
   L"Welcome           = Howdy!",
   L"Welcome           = Welcome to %s version %s.",
   L"Welcome           = This is an early alpha build, and only a few features are working.",
   L"Welcome           = For more info, go to www.mojoware.org.",
   L"DlgAbout          = %s",
   L"DlgAbout          = This is an early alpha version.  Only a few features have been implemented so far.\n",
   L"DlgAbout          = Version %s\n",
   L"DlgAbout          = Built on %s\n",
   L"DlgAbout          = Source code for this program is available under the GNU General Public License version 3.\n",
   L"DlgAbout          = Copyright 2009 Robert Sacks",
   L"DlgAbout.Link         = <a href=\"%s\">Learn more about %s</a>",
   L"DlgMonitor.InputEventsHead      = Your last action",
   L"DlgMonitor.MemosHead       = %s's actions on this PC",
   L"DlgMonitor.ConnectionsHead      = Connections",
   L"DlgSettingsConnection.Title      = %s: Connection settings",
   L"DlgSettingsConnection.Connect.Label    = Connect computers",
   L"DlgSettingsConnection.Connect.Caption   = Are you using this program with one computer or several?",
   L"DlgSettingsConnection.Connect.Yes    = More than one PC",
   L"DlgSettingsConnection.Connect.No    = One PC",
   L"DlgSettingsConnection.AutoFind.Label   = Auto find",
   L"DlgSettingsConnection.AutoFind.Caption   = Do you want this computer to find other computers on your local network automatically and open connections to them?",
   L"DlgSettingsConnection.AutoFind.Yes    = Yes",
   L"DlgSettingsConnection.AutoFind.No    = No",
   L"DlgSettingsConnection.List.Label    = Connection list",
   L"DlgSettingsConnection.List.Caption    = If you wish, you can type names or IP addresses of other computers, each on its own line.  The program will attempt to connect to them.  This is optional because Auto Find (above) usually connects all your computers automatically.",
   L"DlgSettingsConnection.Link      = <a href=\"%s\">Learn more about these choices</a>",
   L"DlgSettingsConnection.MoreOptions    = More Options",
   L"DlgSettingsConnection.OK      = OK",
   L"DlgSettingsConnection.Cancel     = Cancel",
   L"DlgSettingsConnection.RestoreDefaults   = Restore Defaults",
   L"DlgSettingsConnectionAdvanced.Title      = %s: More connection settings",
   L"DlgSettingsConnectionAdvanced.SpecifyLocalIP.Label  = This computer's IP address",
   L"DlgSettingsConnectionAdvanced.SpecifyLocalIP.Caption  = If this computer has more than one IP address, either you or the operating system must choose which one to use.",
   L"DlgSettingsConnectionAdvanced.SpecifyLocalIP.Yes  = I'll choose from the following list:",
   L"DlgSettingsConnectionAdvanced.SpecifyLocalIP.No   = Let the operating system choose.",
   L"DlgSettingsConnectionAdvanced.NetworkOptions.Label  = Network options",
   L"DlgSettingsConnectionAdvanced.UseNagle     = Use Nagle algorithm (default: unchecked)",
   L"DlgSettingsConnectionAdvanced.Port.Label    = Port",
   L"DlgSettingsConnectionAdvanced.Port.Caption    = Don't change the port unless you get an error message saying it's necessary.",
   L"DlgSettingsConnectionAdvanced.Passphrase.Label   = Passphrase",
   L"DlgSettingsConnectionAdvanced.Passphrase.Caption  = A passphrase is optional, but if you use one, it should contain at least 32 characters and spaces.",
   L"DlgSettingsConnectionAdvanced.Link      = <a href=\"%s\">Learn more about these choices</a>",
   L"DlgSettingsConnectionAdvanced.OK      = OK",
   L"DlgSettingsConnectionAdvanced.Cancel     = Cancel",
   L"DlgSettingsConnectionAdvanced.RestoreDefaults   = Restore Defaults",
   L"DlgSettingsConnectionAdvanced.SpecifyLocalIP.Error  = Please select an IP address. You need to do this because\nyou checked \"I'll choose from the following list.\"",
   L"DlgSettingsPerformance.Title                           = %s: Performance settings",
   L"DlgSettingsPerformance.Mojo.Label                      = %s's settings",
   L"DlgSettingsPerformance.System.Label                    = System settings",
   L"DlgSettingsPerformance.Link                            = <a href=\"%s\">Learn more about these choices</a>",
   L"DlgSettingsPerformance.RaiseProcessPriority            = Raise process priority",
   L"DlgSettingsPerformance.MaximizeTimerResolution         = Maximize timer resolution",
   L"DlgSettingsAppearance.Title                            = %s: Appearance settings",
   L"DlgSettingsAppearance.Icon.Label                       = Icons",
   L"DlgSettingsAppearance.ToonIconHeightLabel              = Toon icon height",
   L"DlgSettingsAppearance.ToonIconWidthLabel               = Toon icon width",
   L"DlgSettingsAppearance.WoWIconHeightLabel               = WoW icon height",
   L"DlgSettingsAppearance.WoWIconWidthLabel                = WoW icon width",
   L"DlgSettingsAppearance.Link                             = <a href=\"%s\">Learn more about these choices</a>",
   L"DlgSetTrigger.Link                                     = <a href=\"%s\">Learn more about triggers</a>",
   0
};

